export const GET_ENABLE_SESSION_CONFIG = 'GET_ENABLE_SESSION_CONFIG';
export const GET_ENABLE_SESSION_CONFIG_SUCCESS = 'GET_ENABLE_SESSION_CONFIG_SUCCESS';

export const GET_CURRENT_POS_ID = 'GET_CURRENT_POS_ID';
export const GET_CURRENT_POS_ID_SUCCESS = 'GET_CURRENT_POS_ID_SUCCESS';

export const GET_STAFF_ID = 'GET_STAFF_ID';
export const GET_STAFF_ID_SUCCESS = 'GET_STAFF_ID_SUCCESS';

export const GET_LOCATION_LIST = 'GET_LOCATION_LIST';
export const GET_LOCATION_LIST_SUCCESS = 'GET_LOCATION_LIST_SUCCESS';

export const GET_POS_LIST = 'GET_POS_LIST';
export const GET_POS_LIST_SUCCESS = 'GET_POS_LIST_SUCCESS';

export const SELECT_LOCATION = 'SELECT_LOCATION';
export const SELECT_POS = 'SELECT_POS';

export const ENTER_TO_POS = 'ENTER_TO_POS';
export const ENTER_TO_POS_SUCCESS = 'ENTER_TO_POS_SUCCESS';
export const ENTER_TO_POS_FAIL = 'ENTER_TO_POS_FAIL';