export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GET_LOCATION_NAME = 'GET_LOCATION_NAME';
export const GET_LOCATION_NAME_SUCCESS = 'GET_LOCATION_NAME_SUCCESS';

export const GET_STAFF_NAME = 'GET_STAFF_NAME';
export const GET_STAFF_NAME_SUCCESS = 'GET_STAFF_NAME_SUCCESS';